---
- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Ping servers
    ping:

  - name: Display facts
    debug:
      var: ansible_facts

- hosts: nodes
  become: true
  roles:
    - node_exporter

- hosts: elastic_search
  become: true
  roles:
    - elasticsearch

- hosts: nodes
  become: true
  roles:
    - wazuh_agent

- hosts: nodes
  become: true
  roles:
    - tomcat
